services:
  - type: web
    name: bot-rolls
    env: python
    pythonVersion: 3.11.0
    buildCommand: pip install discord.py python-dotenv flask
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false